# coding: utf-8

"""
    PSI Fytotron Rest API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: todo@todo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fytotron.api.fytotron_api import FytotronApi


class TestFytotronApi(unittest.TestCase):
    """FytotronApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FytotronApi()

    def tearDown(self) -> None:
        pass

    def test_getvar(self) -> None:
        """Test case for getvar

        Returns the current value of the variable
        """
        pass

    def test_info(self) -> None:
        """Test case for info

        Returns all setpoints and actual values in the database.
        """
        pass

    def test_monitor(self) -> None:
        """Test case for monitor

        Returns the current status of the fytotron
        """
        pass

    def test_setvar(self) -> None:
        """Test case for setvar

        Set the setpoint value
        """
        pass


if __name__ == '__main__':
    unittest.main()
