site_name: PSI_Fytotron_API
site_description: python implementation of the PSI fytotron API

theme:
  name: "material"
repo_name: NPEC-NL/PSI-Fytotron-API
repo_url: https://github.com/NPEC-NL/PSI-Fytotron-API

nav:
  - README: "README.md"
  - Docs: 
    - FytotronApi: "docs/FytotronApi.md"
    - InfoValues: "docs/InfoValues.md"
    - MonitorValues: "docs/MonitorValues.md"
