# coding: utf-8

"""
    PSI Fytotron Rest API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: todo@todo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.monitor_values import MonitorValues

class TestMonitorValues(unittest.TestCase):
    """MonitorValues unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MonitorValues:
        """Test MonitorValues
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MonitorValues`
        """
        model = MonitorValues()
        if include_optional:
            return MonitorValues(
                caption = '',
                message = '',
                state = ''
            )
        else:
            return MonitorValues(
        )
        """

    def testMonitorValues(self):
        """Test MonitorValues"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
