# coding: utf-8

"""
    PSI Fytotron Rest API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    Contact: todo@todo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InfoValues(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'max': 'float',
        'min': 'float',
        'name': 'str',
        'unit': 'str',
        'value': 'float'
    }

    attribute_map = {
        'max': 'Max',
        'min': 'Min',
        'name': 'Name',
        'unit': 'Unit',
        'value': 'Value'
    }

    def __init__(self, max=None, min=None, name=None, unit=None, value=None):  # noqa: E501
        """InfoValues - a model defined in Swagger"""  # noqa: E501
        self._max = None
        self._min = None
        self._name = None
        self._unit = None
        self._value = None
        self.discriminator = None
        if max is not None:
            self.max = max
        if min is not None:
            self.min = min
        if name is not None:
            self.name = name
        if unit is not None:
            self.unit = unit
        if value is not None:
            self.value = value

    @property
    def max(self):
        """Gets the max of this InfoValues.  # noqa: E501


        :return: The max of this InfoValues.  # noqa: E501
        :rtype: float
        """
        return self._max

    @max.setter
    def max(self, max):
        """Sets the max of this InfoValues.


        :param max: The max of this InfoValues.  # noqa: E501
        :type: float
        """

        self._max = max

    @property
    def min(self):
        """Gets the min of this InfoValues.  # noqa: E501


        :return: The min of this InfoValues.  # noqa: E501
        :rtype: float
        """
        return self._min

    @min.setter
    def min(self, min):
        """Sets the min of this InfoValues.


        :param min: The min of this InfoValues.  # noqa: E501
        :type: float
        """

        self._min = min

    @property
    def name(self):
        """Gets the name of this InfoValues.  # noqa: E501


        :return: The name of this InfoValues.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InfoValues.


        :param name: The name of this InfoValues.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def unit(self):
        """Gets the unit of this InfoValues.  # noqa: E501


        :return: The unit of this InfoValues.  # noqa: E501
        :rtype: str
        """
        return self._unit

    @unit.setter
    def unit(self, unit):
        """Sets the unit of this InfoValues.


        :param unit: The unit of this InfoValues.  # noqa: E501
        :type: str
        """

        self._unit = unit

    @property
    def value(self):
        """Gets the value of this InfoValues.  # noqa: E501


        :return: The value of this InfoValues.  # noqa: E501
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this InfoValues.


        :param value: The value of this InfoValues.  # noqa: E501
        :type: float
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InfoValues, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InfoValues):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
