# coding: utf-8

"""
    PSI Fytotron Rest API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    Contact: todo@todo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MonitorValues(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'caption': 'str',
        'message': 'str',
        'state': 'str'
    }

    attribute_map = {
        'caption': 'Caption',
        'message': 'Message',
        'state': 'State'
    }

    def __init__(self, caption=None, message=None, state=None):  # noqa: E501
        """MonitorValues - a model defined in Swagger"""  # noqa: E501
        self._caption = None
        self._message = None
        self._state = None
        self.discriminator = None
        if caption is not None:
            self.caption = caption
        if message is not None:
            self.message = message
        if state is not None:
            self.state = state

    @property
    def caption(self):
        """Gets the caption of this MonitorValues.  # noqa: E501


        :return: The caption of this MonitorValues.  # noqa: E501
        :rtype: str
        """
        return self._caption

    @caption.setter
    def caption(self, caption):
        """Sets the caption of this MonitorValues.


        :param caption: The caption of this MonitorValues.  # noqa: E501
        :type: str
        """

        self._caption = caption

    @property
    def message(self):
        """Gets the message of this MonitorValues.  # noqa: E501


        :return: The message of this MonitorValues.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this MonitorValues.


        :param message: The message of this MonitorValues.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def state(self):
        """Gets the state of this MonitorValues.  # noqa: E501


        :return: The state of this MonitorValues.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this MonitorValues.


        :param state: The state of this MonitorValues.  # noqa: E501
        :type: str
        """

        self._state = state

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MonitorValues, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MonitorValues):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
