# coding: utf-8

# flake8: noqa
"""
    PSI Fytotron Rest API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: todo@todo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from fytotron.models.info_values import InfoValues
from fytotron.models.monitor_values import MonitorValues

